/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fcmmhyxjmomcdbniimxu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjbW1oeXhqbW9tY2RibmlpbXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMzYzMTgsImV4cCI6MjA4NTYxMjMxOH0.BEB58h_rxNR-EyPqpgvAh-w5puyJS17XPMuO38KbyN4"